### ISSUE TITLE
Plase can you add some new function to this libarry

### ISSUE THREAD

**Issue by LMJayasundara** [evanshortiss/vector2d#6]
All Vector Functions :

Dynamic Vector define like:
    **const vec = ();**
Clear the all vector value like:
    **vec.clear();**
Rezise the dynamaic vector like:
    **vec.resizee(value);**

src from https://www.geeksforgeeks.org/vector-in-cpp-stl/  **Vector in C++ STL**

Your work grate..
Thank you..

**Comment by evanshortiss** [comment]
I'm not sure I understand @Shanmax1996. This library is not really comparable to the C++ std:vector. 

This is a 2D vector implementation used for simple math/physics/graphics and isn't a container for iterables.

**Comment by evanshortiss** [comment]
I'm not sure I understand @Shanmax1996. This library is not really comparable to the C++ std:vector. 

This is a 2D vector implementation used for simple math/physics/graphics and isn't a container for iterables.

**Comment by LMJayasundara** [comment]
Ok I got it..
Thank for your reply..

Can I customize this library..For a example can I remove some part and
customize things..

**Comment by evanshortiss** [comment]
@Shanmax1996 feel free to fork it and customise as you want. If you think the changes you made are valuable I'd be happy to review and merge PRs
